### ISSUE TITLE
JS-深入数组005-6扩展运算符，这个扁平化是否存在问题

### ISSUE THREAD

**Issue by Amb1t0in** [sanyuan0704/my_blog#13]
some函数应传入函数，改为
```javascript
while (ary.some(Array.isArray)) {
  ary = [].concat(...ary);
}
```
望请指教

**Comment by sanyuan0704** [comment]
确实，这里我笔误了

**Comment by boyongjiong** [comment]
@sanyuan0704 
![image](https://user-images.githubusercontent.com/8553969/81249884-55d59480-9052-11ea-9578-6577e3c02aa1.png)还有这个，多了一个 ')' 括号
