### ISSUE TITLE
网站似乎挂了

### ISSUE THREAD

**Issue by HongYufan** [sanyuan0704/my_blog#19]
访问提示 Cannot GET /js-base/003.html

**Comment by sanyuan0704** [comment]
统一回复，博客已重构。直接在访问/my_blog路径即可


---原始邮件---
发件人: &quot;Yufan&quot;<notifications@github.com&gt;
发送时间: 2020年11月18日(周三) 中午12:27
收件人: &quot;sanyuan0704/my_blog&quot;<my_blog@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [sanyuan0704/my_blog] 网站似乎挂了 (#19)




 
访问提示 Cannot GET /js-base/003.html
 
&mdash;
